################################################################################
# Secrets sample file
################################################################################
# Tutorial:     https://youtu.be/D9veJLKqnpg
# -----------------------------------------------------------------------------      
# Author: Pascal Parent
# Company: Home Automator (ZA)
# Web: https://www.youtube.com/@homeautomatorza
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Use at your own risks!
################################################################################

#Api
api_encryption_key: "key"

#OTA
ota_password: "key"

# Your Wi-Fi SSID and password
wifi_ssid: "IOT-SSID"
wifi_password: "password"
ap_password: "password"

# Network settings
gateway_address: 192.168.1.1
subnet_address: 255.255.255.0
dns_address: 192.168.1.1